const state={catalog:[],type:'skill',category:'all',query:'',selected:null,content:'',view:'preview'};
const el={catalog:document.querySelector('#catalog'),categories:document.querySelector('#categories'),search:document.querySelector('#search'),skillCount:document.querySelector('#skill-count'),promptCount:document.querySelector('#prompt-count'),sectionEyebrow:document.querySelector('#section-eyebrow'),sectionTitle:document.querySelector('#section-title'),resultCount:document.querySelector('#result-count'),empty:document.querySelector('#empty-state'),clearFilters:document.querySelector('#clear-filters'),detail:document.querySelector('#detail'),detailPath:document.querySelector('#detail-path'),detailKind:document.querySelector('#detail-kind'),detailTitle:document.querySelector('#detail-title'),detailDescription:document.querySelector('#detail-description'),detailTags:document.querySelector('#detail-tags'),detailGithubTop:document.querySelector('#detail-github-top'),openGithub:document.querySelector('#open-github'),copyContent:document.querySelector('#copy-content'),copyAppLink:document.querySelector('#copy-app-link'),copySourceLink:document.querySelector('#copy-source-link'),contentLoading:document.querySelector('#content-loading'),preview:document.querySelector('#markdown-preview'),raw:document.querySelector('#raw-content'),toast:document.querySelector('#toast')};
const categoryLabels={'interface-design':'Interface design','motion-animation':'Motion & animation','svg-vector':'SVG & vector','interactive-worlds':'Interactive worlds','rendering':'Rendering','research':'Research','web-prototypes':'Web prototypes','visual-assets':'Visual assets'};
function titleCase(value){return categoryLabels[value]||value.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function githubUrl(item){return `https://github.com/endpuppet/agent-shelf/blob/main/${item.path}`}
function routeFor(item){return `#/${item.type}s/${item.category}/${item.slug}`}
function appUrl(item){return `${location.origin}${location.pathname}${routeFor(item)}`}
function stripFrontmatter(markdown){return markdown.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/,'')}
function renderMarkdown(markdown){const clean=stripFrontmatter(markdown);if(window.marked&&window.DOMPurify){marked.setOptions({gfm:true,breaks:false});return DOMPurify.sanitize(marked.parse(clean),{USE_PROFILES:{html:true}})}return `<pre><code>${clean.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</code></pre>`}
function toast(message){el.toast.textContent=message;el.toast.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove('is-visible'),1700)}
async function copyText(text,success){try{await navigator.clipboard.writeText(text);toast(success)}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();toast(success)}}
function counts(){el.skillCount.textContent=state.catalog.filter(i=>i.type==='skill').length;el.promptCount.textContent=state.catalog.filter(i=>i.type==='prompt').length}
function categoriesForType(){return[...new Set(state.catalog.filter(i=>i.type===state.type).map(i=>i.category))]}
function renderCategories(){const categories=categoriesForType();if(state.category!=='all'&&!categories.includes(state.category))state.category='all';el.categories.innerHTML=[`<button class="category-chip ${state.category==='all'?'is-active':''}" data-category="all">All</button>`,...categories.map(cat=>`<button class="category-chip ${state.category===cat?'is-active':''}" data-category="${cat}">${titleCase(cat)}</button>`)].join('');el.categories.querySelectorAll('[data-category]').forEach(button=>{button.addEventListener('click',()=>{state.category=button.dataset.category;renderCategories();renderCatalog()})})}
function filteredItems(){const q=state.query.trim().toLowerCase();return state.catalog.filter(item=>{if(item.type!==state.type)return false;if(state.category!=='all'&&item.category!==state.category)return false;if(!q)return true;return[item.title,item.description,item.category,...(item.tags||[])].join(' ').toLowerCase().includes(q)})}
function cardMarkup(item,index){const accent=item.type==='skill'?'var(--accent)':'var(--warm)';return `<article class="card" data-id="${item.id}" tabindex="0" role="button" aria-label="Open ${item.title}" style="--card-accent:${accent};animation-delay:${Math.min(index*28,180)}ms"><div class="card-top"><span class="card-kind">${titleCase(item.category)}</span><span class="card-arrow" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></span></div><h3>${item.title}</h3><p>${item.description}</p><div class="card-tags">${(item.tags||[]).slice(0,3).map(tag=>`<span class="tag">${tag}</span>`).join('')}</div></article>`}
function renderCatalog(){const items=filteredItems(),typeLabel=state.type==='skill'?'Skills':'Prompts';el.sectionEyebrow.textContent=typeLabel;el.sectionTitle.textContent=state.category==='all'?`All ${typeLabel.toLowerCase()}`:titleCase(state.category);el.resultCount.textContent=`${items.length} ${items.length===1?'item':'items'}`;el.catalog.innerHTML=items.map(cardMarkup).join('');el.empty.hidden=items.length!==0;el.catalog.querySelectorAll('.card').forEach(card=>{const open=()=>openItem(state.catalog.find(i=>i.id===card.dataset.id));card.addEventListener('click',open);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}})})}
async function loadContent(item){el.contentLoading.hidden=false;el.preview.hidden=true;el.raw.hidden=true;try{const response=await fetch(`./${item.path}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.content=await response.text();el.preview.innerHTML=renderMarkdown(state.content);el.raw.querySelector('code').textContent=state.content;el.contentLoading.hidden=true;setContentView(state.view)}catch(error){el.contentLoading.hidden=true;el.preview.hidden=false;el.preview.innerHTML=`<p>Could not load this file. <a href="${githubUrl(item)}" target="_blank" rel="noreferrer">Open the GitHub source instead.</a></p>`;console.error(error)}}
function setContentView(view){state.view=view;document.querySelectorAll('.content-tab').forEach(tab=>{const active=tab.dataset.view===view;tab.classList.toggle('is-active',active);tab.setAttribute('aria-selected',active?'true':'false')});el.preview.hidden=view!=='preview';el.raw.hidden=view!=='raw'}
function openItem(item,{updateHash=true}={}){if(!item)return;state.selected=item;state.content='';state.view='preview';el.detailPath.textContent=item.path;el.detailKind.textContent=`${item.type} · ${titleCase(item.category)}`;el.detailKind.style.color=item.type==='skill'?'var(--accent)':'var(--warm)';el.detailTitle.textContent=item.title;el.detailDescription.textContent=item.description;el.detailTags.innerHTML=(item.tags||[]).map(tag=>`<span class="tag">${tag}</span>`).join('');const source=githubUrl(item);el.detailGithubTop.href=source;el.openGithub.href=source;el.detail.classList.add('is-open');el.detail.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(updateHash)history.pushState(null,'',routeFor(item));loadContent(item)}
function closeDetail({updateHash=true}={}){state.selected=null;el.detail.classList.remove('is-open');el.detail.setAttribute('aria-hidden','true');document.body.style.overflow='';if(updateHash)history.pushState(null,'',`#/${state.type}s`)}
function applyHash(){const parts=location.hash.replace(/^#\//,'').split('/').filter(Boolean);if(!parts.length)return;state.type=parts[0]==='prompts'?'prompt':'skill';document.querySelectorAll('.type-tab').forEach(tab=>{const active=tab.dataset.type===state.type;tab.classList.toggle('is-active',active);tab.setAttribute('aria-selected',active?'true':'false')});state.category='all';renderCategories();renderCatalog();if(parts.length>=3){const[,category,slug]=parts,item=state.catalog.find(i=>i.type===state.type&&i.category===category&&i.slug===slug);if(item)openItem(item,{updateHash:false})}else if(state.selected)closeDetail({updateHash:false})}
async function init(){try{const response=await fetch('./catalog.json',{cache:'no-store'});if(!response.ok)throw new Error(`Catalog HTTP ${response.status}`);const data=await response.json();state.catalog=data.items;counts();renderCategories();renderCatalog();applyHash()}catch(error){el.catalog.innerHTML=`<div class="empty-state"><h3>Catalog failed to load.</h3><p>${error.message}</p></div>`;console.error(error)}}
document.querySelectorAll('.type-tab').forEach(tab=>{tab.addEventListener('click',()=>{state.type=tab.dataset.type;state.category='all';document.querySelectorAll('.type-tab').forEach(t=>{const active=t===tab;t.classList.toggle('is-active',active);t.setAttribute('aria-selected',active?'true':'false')});history.replaceState(null,'',`#/${state.type}s`);renderCategories();renderCatalog()})});
el.search.addEventListener('input',event=>{state.query=event.target.value;renderCatalog()});el.clearFilters.addEventListener('click',()=>{state.query='';state.category='all';el.search.value='';renderCategories();renderCatalog()});document.querySelectorAll('[data-close-detail]').forEach(button=>button.addEventListener('click',()=>closeDetail()));document.querySelectorAll('.content-tab').forEach(tab=>tab.addEventListener('click',()=>setContentView(tab.dataset.view)));el.copyContent.addEventListener('click',()=>state.selected&&copyText(state.content,'Content copied'));el.copyAppLink.addEventListener('click',()=>state.selected&&copyText(appUrl(state.selected),'Shelf link copied'));el.copySourceLink.addEventListener('click',()=>state.selected&&copyText(githubUrl(state.selected),'Source link copied'));window.addEventListener('hashchange',applyHash);window.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.selected)closeDetail();if(event.key==='/'&&!state.selected&&document.activeElement?.tagName!=='INPUT'){event.preventDefault();el.search.focus()}});init();